create extension if not exists pgcrypto;

create table if not exists x_accounts (
  id uuid primary key default gen_random_uuid(),
  slug text not null unique,
  display_name text not null,
  posting_hour_utc smallint not null check (posting_hour_utc between 0 and 23),
  posting_minute_utc smallint not null check (posting_minute_utc between 0 and 59),
  enabled boolean not null default true,
  current_cycle integer not null default 1,
  x_api_key text not null,
  x_api_key_secret text not null,
  x_access_token text not null,
  x_access_token_secret text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists post_contents (
  id bigint generated by default as identity primary key,
  account_id uuid not null references x_accounts(id) on delete cascade,
  content text not null,
  link text null,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists idx_post_contents_account_content_link
  on post_contents(account_id, content, coalesce(link, ''));

create table if not exists x_account_post_history (
  id bigint generated by default as identity primary key,
  account_id uuid not null references x_accounts(id) on delete cascade,
  post_content_id bigint not null references post_contents(id) on delete cascade,
  cycle_no integer not null,
  created_at timestamptz not null default now()
);

create unique index if not exists idx_history_unique_cycle
  on x_account_post_history(account_id, post_content_id, cycle_no);

create table if not exists x_post_logs (
  id bigint generated by default as identity primary key,
  account_id uuid not null references x_accounts(id) on delete cascade,
  post_content_id bigint null references post_contents(id) on delete set null,
  status text not null check (status in ('success', 'failed')),
  posted_text text null,
  x_post_id text null,
  error_message text null,
  created_at timestamptz not null default now()
);

create table if not exists short_links (
  id bigint generated by default as identity primary key,
  original_url text not null unique,
  short_url text not null,
  created_at timestamptz not null default now()
);

create or replace function set_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

drop trigger if exists trg_post_contents_updated_at on post_contents;
create trigger trg_post_contents_updated_at
before update on post_contents
for each row execute function set_updated_at();

drop trigger if exists trg_x_accounts_updated_at on x_accounts;
create trigger trg_x_accounts_updated_at
before update on x_accounts
for each row execute function set_updated_at();
