-- post_contents.account_id を id の直後へ並べ替える移行
-- PostgreSQLは列順を直接変更できないため、テーブル再作成で対応する
-- 実行中は post_contents / x_account_post_history / x_post_logs にロックがかかる

begin;

-- 依存FKを一時的に外す
alter table if exists x_account_post_history
  drop constraint if exists x_account_post_history_post_content_id_fkey;

alter table if exists x_post_logs
  drop constraint if exists x_post_logs_post_content_id_fkey;

-- 旧テーブルを退避
alter table post_contents rename to post_contents_old;

-- 旧テーブル側の同名インデックスを落として名前衝突を回避
drop index if exists idx_post_contents_account_content_link;

-- 列順を指定して新テーブル作成
create table post_contents (
  id bigint generated by default as identity,
  account_id uuid not null references x_accounts(id) on delete cascade,
  content text not null,
  link text null,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint post_contents_pkey_new primary key (id)
);

-- データ移行
insert into post_contents (id, account_id, content, link, is_active, created_at, updated_at)
select id, account_id, content, link, is_active, created_at, updated_at
from post_contents_old;

-- identityシーケンスを現在値へ合わせる
select setval(
  pg_get_serial_sequence('post_contents', 'id'),
  coalesce((select max(id) from post_contents), 1),
  true
);

-- 一意インデックス再作成
create unique index if not exists idx_post_contents_account_content_link
  on post_contents(account_id, content, coalesce(link, ''));

-- updated_at トリガー再作成
drop trigger if exists trg_post_contents_updated_at on post_contents;
create trigger trg_post_contents_updated_at
before update on post_contents
for each row execute function set_updated_at();

-- 依存FKを復元
alter table x_account_post_history
  add constraint x_account_post_history_post_content_id_fkey
  foreign key (post_content_id) references post_contents(id) on delete cascade;

alter table x_post_logs
  add constraint x_post_logs_post_content_id_fkey
  foreign key (post_content_id) references post_contents(id) on delete set null;

-- 旧テーブルを削除
drop table post_contents_old;

commit;
