create table if not exists priority_post_queue (
  id bigint generated by default as identity primary key,
  account_id uuid not null references x_accounts(id) on delete cascade,
  post_content_id bigint not null references post_contents(id) on delete cascade,
  created_at timestamptz not null default now()
);

create index if not exists idx_priority_post_queue_account_id_id
  on priority_post_queue(account_id, id);
